feat(authentication): social login and register
andela/ah-frontend-dojo pull request #18
Opened 2019-06-06 10:08 UTC by JamesMudidi

**What does this PR do?**

- Implements user signup and signin using social authentication

**Description of Task to be completed?**

- [ ] create login buttons for facebook and google
- [ ] create login actions for facebook and google
- [ ] test login buttons
- [ ] test login actions

**How should this be manually tested?**

- Navigate to the login route and click on the facebook button

**Any background context you want to provide?**

- This is currently a work in progress. Many things are still being fixed and refactored 

**What are the relevant pivotal tracker stories?**

- [#165273530](https://www.pivotaltracker.com/story/show/165273530)

**Screenshots (if appropriate)**
<img width="1440" alt="Screenshot 2019-06-06 at 1 06 53 PM" src="https://user-images.githubusercontent.com/39102955/59025089-0ee88900-885c-11e9-8322-c10e3b45fdb7.png">

2019-06-13 12:41 UTC, kalsmic requested changes
Well done, @JamesMudidi, please kindly consider looking into these issues.

2019-06-13 12:41 UTC, kalsmic commented on src/components/Login/index.js
> +import GoogleButtons from '../Social/Google/Google';
@JamesMudidi, please consider revising the imports to
```
import FaceBookButton from 'components/Social/Facebook/Facebook';
import GoogleButtons from 'components/Social/Google/Google';
```

2019-06-13 12:41 UTC, kalsmic commented on src/components/Social/Google/GoogleStyle.scss
> +}
Please also kindly consider adding a line at the end of the file.

2019-06-14 06:38 UTC, llwasampijja requested changes
Good work @JamesMudidi on the implementation of the feature as far. However, it would be nice if you documented your code. Otherwise kudos!

2019-06-14 16:24 UTC, closed without merging